# Generated by Django 3.2.4 on 2021-06-21 09:53

from django.db import migrations, models
import emailapp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=100, verbose_name='From Email')),
                ('to_email', models.EmailField(max_length=100, verbose_name='To Email')),
                ('subject', models.CharField(max_length=300, verbose_name='Subject')),
                ('body_text', models.TextField(max_length=5000, verbose_name='Body Text')),
                ('sent_via', models.IntegerField(blank=True, choices=[(1, 'Amazon SES'), (2, 'Google SMTP'), (3, 'SendGrid')], default=1, null=True)),
                ('created', models.DateTimeField(default=emailapp.utils.get_localtime)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
